// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTSn7PC0wGqGMSsJjdSCrhZKIiriN4N0',
    appId: '1:621495135806:web:48735e5c38ee14167fab6f',
    messagingSenderId: '621495135806',
    projectId: 'secretsantadb-ad295',
    authDomain: 'secretsantadb-ad295.firebaseapp.com',
    storageBucket: 'secretsantadb-ad295.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDSKs5dzNFYAVpd6FN3U5llyzBIHDaI4',
    appId: '1:621495135806:android:8887c9dc38fb7e917fab6f',
    messagingSenderId: '621495135806',
    projectId: 'secretsantadb-ad295',
    storageBucket: 'secretsantadb-ad295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQTTc5Y7G07Lfrqw7EEdrBFZFs5_i8PM',
    appId: '1:621495135806:ios:82f7cb498a425d037fab6f',
    messagingSenderId: '621495135806',
    projectId: 'secretsantadb-ad295',
    storageBucket: 'secretsantadb-ad295.appspot.com',
    iosBundleId: 'com.example.secretsanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQTTc5Y7G07Lfrqw7EEdrBFZFs5_i8PM',
    appId: '1:621495135806:ios:f29d9a6ba3fb081b7fab6f',
    messagingSenderId: '621495135806',
    projectId: 'secretsantadb-ad295',
    storageBucket: 'secretsantadb-ad295.appspot.com',
    iosBundleId: 'com.example.secretsanta.RunnerTests',
  );
}
